import "~/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <TRPCReactProvider>
        <html
          lang="en"
          className={`${GeistSans.variable} select-none overflow-hidden`}
        >
          <Script id="disable-context" strategy="afterInteractive">
            {`document.addEventListener('contextmenu', (e) => e.preventDefault());`}
          </Script>
          <body>{children}</body>
        </html>
      </TRPCReactProvider>
    </ClerkProvider>
  );
}
